#!/bin/bash

# make new files and scripts excutable
sudo chmod +x /usr/share/pidesktop/script/*
sudo chmod +x /usr/share/pidesktop/python/*

# links to make running manual installation steps easy
sudo ln -sv /usr/share/pidesktop/script/pd_check /usr/bin/pd_check
sudo ln -sv /usr/share/pidesktop/script/pd_clonessd /usr/bin/pd_clonessd
sudo ln -sv /usr/share/pidesktop/python/pd_bootssd.py /usr/bin/pd_bootssd
sudo ln -sv /usr/share/pidesktop/python/pd_fixrtc.py /usr/bin/pd_fixrtc

# enable new sevices
sudo systemctl enable pidesktop-powerkey.service
sudo systemctl enable pidesktop-reboot.service
sudo systemctl enable pidesktop-shutdown.service
sudo systemctl list-unit-files | grep pidesktop

# uncomment to autoclone SD to SSD
#sudo /usr/share/pidesktop/python/pd_clonessd.py

# fix up the rtc by default
sudo /usr/share/pidesktop/python/pd_fixrtc.py
